apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservice-devops-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/yoav7000/gitops-devops-project.git
      revision: HEAD
      files:
      - path: environments/**/cluster-config/cluster-config.json
      values:
        env_name: "{{index .path.segments 1}}"
  template:
    metadata:
      name: "microservice-devops-{{.values.env_name}}"
    spec:
      project: {{.values.env_name}}
      source:
        repoURL: https://github.com/yoav7000/gitops-devops-project.git
        targetRevision: HEAD
        path: charts/devops-project-helm-chart
        helm:
          valueFiles:
          - '/environments/{{.values.env_name}}/values/microservice-devops-values.yaml'
      destination:
        name: "{{.cluster.name}}"
        namespace: '{{.values.env_name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true