apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservice-devops-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/yoav7000/gitops-devops-project.git
      revision: HEAD
      files:
      - path: environments/**/cluster-config/cluster-config.json
      values:
        env: "{{index .path 1}}"
  template:
    metadata:
      name: "microservice-devops-{{.values.env}}"
    spec:
      project: "{{.values.env}}"
      source:
        repoURL: https://github.com/yoav7000/gitops-devops-project.git
        targetRevision: HEAD
        path: charts/devops-project-helm-chart
        helm:
          valueFiles:
          - '/{{.path.path}}/values/microservice-devops-values.yaml'
      destination:
        server: "{{.cluster.name}}"
        namespace: '{{.values.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true