
replicaCount: 3

image:
  repository: yoav7001/devops-project
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "985d9694275a5e67edb53169da2bbc2d2a1083c5"

# Existing image pull secrets names.
imagePullSecrets: [{"name": "yoav-image-pull-secret"}]

env:
  ENVIRONMENT: "DEV"

sealedsecret:
  hello: | 
    AgBSyh3UyVJTt114QfY1ewPFAxzXkoy++/WbZVBoRzm0ze9hlvkQkfF2n89UtemfBJ1dKK//Y1NEbYpuMyXkbD0AKzNRFTBCeiaBVDL89OVFfZhqRD++mz6/QGCEK/p55jD5zPcAHVO/qNUFGN+Qe0Yqwso6nX9vHJxzfX/ppqXgj06TekukUAgQDTK2vQm4tfBjU13B8gMX6ITCcpqFAM5/hjD50KOI5jjxPWfk2uwI8HMaRJCThyDYnEzuvAQ3wetqoLJfMf0MC3mQhsQohm/Hf25RK42VS7LgCfTTRxuXBC1Vk8UqMrEZwt9SG4k/SsEqlNFUg+sfpjzdtMsG4CuSg76O0fqwi1g1UIGEQiMsgI2XjQxC2PF+lmgiSAWA1DfDEMTOzoHRmKqecIUEpnS2OnCsGThGDHsbmXGX31X3U+qDtKS5gX+SvU3CbLHZH5H1T3/PnJ5N3Rj9Ff1FdoWpF9uqdIZgbMBPlfYawWQJe1Li9op4EszLIgUCcAMYFN1h2CLioJae++6Iq4XQlxQcQt6k6MtnmKLX3Har1Zk1wFlF4+Y9Btk9Mb52bib1+1x7haT4eMbWj4imlMueD84yawM7h4YgEcwsQ3Xb3JX+UrNsHcVm8a78BiNj9H60YkQcArEIrFO+s5rYvyOzrB34OQkqK5FHnbhRSX0ZvoCRdO5eMLwqTmWqKAuzxXJoiAFYBrT3mYHAK44=

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  hosts:
    - host: dev.ori.yoav.com
      paths:
        - path: /

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1
  # targetMemoryUtilizationPercentage: 80
