
replicaCount: 3

image:
  repository: yoav7001/devops-project
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "985d9694275a5e67edb53169da2bbc2d2a1083c5"

# Existing image pull secrets names.
imagePullSecrets: [{"name": "yoav-image-pull-secret"}]

env:
  ENVIRONMENT: "DEV"

# sealedsecret:
#   hello: | 
#     AgC5qkg71Zm3KIKN/4cOEUrKcv3pPwPvcyVk5r4+cxyMYNFVezx+0inCsozJtbUSaVaHPD0Pcnn2eBalC4BPyEGdX1kJ3SFzQaAGh1h6NifaYC6GeDtwAbmEOMA/0h/+bzqXVShXUirKyiRc4jtJJ0rSMtbGfCXFGwvdz4ocKv3XJXSdswVTfDAlq0kHSs50kM1R/yf88Jtsat6oJgBGsaqbf9RL2XYIQbyDRblvRBXGsV1pjgfiTrtbIkTuADGH/MyNK21FbsMwbXvyxAwI0zwsbbhvWtvU451E2eN1I62dDsz5oPF/otDYiKPVYUSBLC6ygbZJgImPE7uMRHfMzEfM9ieWLePQ/GIzruQds0PWKuNhfwrquO91P+DSf4HQ1yob36wf7Pr2J8An0h+wRL7ca2f1hn6f73UW3ihe6bnjPDnvpgBGxRzK2g4mjF1EhJr9i7L3TCg19psqLeCEL8/YlMMv3Itpj/Q8Ze4Qb9wmevPnLM3kgLDwjxLWhX8ujal4ykx2jdsUrfzyIr2sutqRi5QSCXf3lCpaRxk4140eGNu+aVv1YpaC23STarBdk9mnGaASc8gsBLEZBQqxOqnxovSf1C7jhhw/aMJu9RSeX7xqmUn+99GUnGGd7v1277Xm5g31/c6U8LUPFBvVM68x6f//aSqY10dwP8UEfOvDTR3xyYL0UT6T7q50I590f8ivRgeC4bYqkyQ=

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  hosts:
    - host: dev.ori.yoav.com
      paths:
        - path: /

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1
  # targetMemoryUtilizationPercentage: 80
