{{- with .Values.sealedsecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Release.Name }}-sealedsecret
  labels:
    app: {{ $.Release.Name }}
spec:
  encryptedData:
    {{- range $key, $value := . }}
        {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}