{{- with .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
  labels:
    app: {{ $.Release.Name }}
type: Opaque
data:
  {{- range $key, $value := . }}
            {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}